### ISSUE TITLE
Make it possible to use other JSCS versions

### ISSUE THREAD

**Issue by al-broco** [al-broco/mimosa-jscs#11]
Currently mimosa-jscs is hard locked to a particular JSCS version. This is unfortunate since JSCS sometimes changes its set of rules, adding or changing rules and deprecating old rules. A user may have a JSCS configuration that requires a particular JSCS version.

It would be good if JSCS version could be specified in the mimosa-jscs plugin config. If that is not possible, mimosa-jscs can perhaps use any installed JSCS version and not have a dependency.

This could be tricky since mimosa-jscs uses JSCS' JS API, which is not documented and thus can change at any time.

**Comment by dbashford** [comment]
You just addressed this yeah?

**Comment by al-broco** [comment]
Yes, v2.0.0 supports choosing a JSCS version since JSCS is now a peer dependency of mimosa-jscs.
