### ISSUE TITLE
Provide ability to run before or after compile?

### ISSUE THREAD

**Issue by dbashford** [al-broco/mimosa-jscs#13]
Right now this runs `afterCompile` and it runs on `outputFileText`.  The problem with this is that you will possibly be running jscs against transpiled files.  So, for instance, if you are using [Babel](http://babeljs.io/), you are stuck with any possibly JSCS problems that arise because of the transpiled output.  (For instance, babel transforms all quotes to double-quotes, but we prefer single quotes and have JSCS set up to catch that.)

I think its valid to have an option in the config to run this either `beforeCompile` on the `inputFileText` or `afterCompile` on the `outputFileText`.

I personally think `beforeCompile` is the most common use case and maybe should be the default, but I can be swayed in the other direction. =p

**Comment by dbashford** [comment]
Would you be open to getting this as a PR?  My only issue is updating tests.  I know exactly what code should be updated and how, but not sure I have time to also figure out the testing suite such that I can get the updates tested too.

**Comment by al-broco** [comment]
Wouldn't this change make mimosa-jscs behave differently than other linting modules, such as mimosa-jshint? mimosa-jshint lints on afterCompile and I think it's a good thing that two modules that do very similar things have the same configuration and behavior, or as similar config/behavior as possible.

Also, wouldn't linting on beforeCompile break linting of (for instance) compiled CoffeeScript if the compiled config option is set to true?

**Comment by dbashford** [comment]
The idea is to be flexible.

The kind of thing JSCS checks is different in some ways than JSHint.  "Style" is more likely to change via transpiling.  Babel, I've found, does all kinds of things that absolutely kill us from a JSCS perspective.  Our codebase, when run through babel, goes from generating 0 JSCS to 3000+ which  makes JSCS unusable.

So I'm cool, if you want, to leave the default the way things are now, but it would be nice to be able to run on the input text.

If you have coffeescript, then naturally you would only run afterCompile.  But if you are ES6 code you are transpiling, then running before compiling is ideal.

**Comment by al-broco** [comment]
That's a good point. In fact, it might have been a mistake to mimic mimosa-jshint's compiled option in mimosa-jscs. I have a hard time thinking of a useful use-case for style-checking (for instance) compiled CoffeeScript.

I think I'm OK with adding the option. I would welcome a PR if you have a suggestion. I want to add tests of the new option before making a release.

I think it makes sense to make the old behavior the default, mainly to be backwards compatible (and avoiding a major release).

Also, I think you should consider adding the option to mimosa-jshint and the other static check modules.

**Comment by dbashford** [comment]
I'm happy to add the functionality as a PR.  We need this ASAP so we can start using babel with our stack, so we can just point to my fork while you work out anything you want to get in afterwards.

**Comment by al-broco** [comment]
Pull request merged and included in v2.2.0. Thanks!
